# Generated by Django 3.2.8 on 2022-10-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rackAzure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('explanation', models.CharField(max_length=10000)),
                ('tips_and_tricks', models.CharField(max_length=250)),
                ('code', models.TextField(null=True)),
            ],
        ),
    ]
