# Generated by Django 3.2.8 on 2022-10-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rackAzure',
            new_name='rack_Azure',
        ),
    ]
